language: java

jdk:
  - openjdk8
  - openjdk11

env:
  - ECLIPSE_TARGET_PLATFORM=Eclipse-4.8
  - ECLIPSE_TARGET_PLATFORM=Eclipse-2020-03
  - ECLIPSE_TARGET_PLATFORM=Eclipse-2020-06
  - ECLIPSE_TARGET_PLATFORM=Eclipse-2020-09

install: true

script: mvn -Dtarget.platform=$ECLIPSE_TARGET_PLATFORM clean verify
