# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

strategy:
  matrix:
    eclipse_4_8:
      ECLIPSE_TARGET_PLATFORM: 'Eclipse-4.8'
    eclipse_2018_12:
      ECLIPSE_TARGET_PLATFORM: 'Eclipse-2018-12'
    eclipse_2019_06:
      ECLIPSE_TARGET_PLATFORM: 'Eclipse-2019-06'
    eclipse_2019_09:
      ECLIPSE_TARGET_PLATFORM: 'Eclipse-2019-09'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: '-Dtarget.platform=$(ECLIPSE_TARGET_PLATFORM) clean verify'
